---

- name: Configure apache
  become: true
  become_method: sudo
  hosts: app
  roles:
   - role: 'ansible-apache'
  tasks: 
   - command: hostname -I
     register: command_output

- name: Configure nginx
  become: true
  become_method: sudo
  hosts: web
  roles:
   - role: 'ansible-nginx'
