---
# tasks file for ansible-nginx
- include_tasks: nginx_AMI.yml

- name: Ensure nginx service is running as configured.
  service:
    name: nginx
    state: "{{ nginx_service_state }}"
    enabled: "{{ nginx_service_enabled }}"
