---
# tasks file for ansible-apache
- include_tasks: apache.yml

- name: Ensure Apache has selected state and enabled on boot.
  service:
    name: "{{ apache_service }}"
    state: "{{ apache_state }}"
    enabled: true
