---
# handlers file for ansible-nginx

- name: restart nginx
  service: name=nginx state=restarted
  become: true
  become_user: sudo

- name: validate nginx configuration
  command: nginx -t -c /etc/nginx/nginx.conf
  changed_when: false
  become: true
  become_user: sudo

- name: reload nginx
  service: name=nginx state=reloaded
  become: true
  become_user: sudo
